CREATE DATABASE MUSIC_STORE;
USE MUSIC_STORE;

-- 1. Genre and MediaType
CREATE TABLE GENRE(
	GENRE_ID INT PRIMARY KEY,
	NAME VARCHAR(120)
);
SELECT * FROM GENRE;

CREATE TABLE MEDIATYPE (
	MEDIA_TYPE_ID INT PRIMARY KEY,
	NAME VARCHAR(120)
);
SELECT * FROM MEDIATYPE;

-- EMPLOYEE
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT PRIMARY KEY,
    LAST_NAME VARCHAR(120),
    FIRST_NAME VARCHAR(120),
    TITLE VARCHAR(120),
    REPORTS_TO INT,
    LEVELS VARCHAR(255),
    BIRTHDATE DATE,
    HIRE_DATE DATE,
    ADDRESS VARCHAR(255),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    COUNTRY VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    PHONE VARCHAR(50),
    FAX VARCHAR(50),
    EMAIL VARCHAR(100)
);

SELECT * FROM EMPLOYEE;
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/employee.csv'
IGNORE
INTO TABLE EMPLOYEE
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

UPDATE EMPLOYEE
SET BIRTHDATE='1961-01-26'
WHERE EMPLOYEE_ID=9;
UPDATE EMPLOYEE
SET HIRE_DATE='2016-01-14'
WHERE EMPLOYEE_ID=9;




CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(120),
    LAST_NAME VARCHAR(120),
    COMPANY VARCHAR(120),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    COUNTRY VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    PHONE VARCHAR(50),
    FAX VARCHAR(50),
    EMAIL VARCHAR(100),
    SUPPORT_REP_ID INT,
    FOREIGN KEY (SUPPORT_REP_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);
SELECT * FROM CUSTOMER;


-- 4. ARTIST
CREATE TABLE ARTIST (
    ARTIST_ID INT PRIMARY KEY,
    NAME VARCHAR(120)
);
SELECT * FROM ARTIST;


-- 5. ALBUM
CREATE TABLE ALBUM (
    ALBUM_ID INT PRIMARY KEY,
    TITLE VARCHAR(160),
    ARTIST_ID INT,
    FOREIGN KEY (ARTIST_ID) REFERENCES ARTIST(ARTIST_ID)
);
SELECT * FROM ALBUM;

-- 6. TRACK
CREATE TABLE TRACK (
    TRACK_ID INT PRIMARY KEY,
    NAME VARCHAR(200),
    ALBUM_ID INT,
    MEDIA_TYPE_ID INT,
    GENRE_ID INT,
    COMPOSER VARCHAR(220),
    MILLISECONDS INT,
    BYTES INT,
    UNIT_PRICE DECIMAL(10,2),
    FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM(ALBUM_ID),
    FOREIGN KEY (MEDIA_TYPE_ID) REFERENCES MEDIATYPE(MEDIA_TYPE_ID),
    FOREIGN KEY (GENRE_ID) REFERENCES GENRE(GENRE_ID)
);

SHOW VARIABLES LIKE 'secure_file_priv';
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/track.csv'
INTO TABLE TRACK
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(TRACK_ID, NAME, ALBUM_ID, MEDIA_TYPE_ID, GENRE_ID, COMPOSER, MILLISECONDS, BYTES, UNIT_PRICE);

SELECT * FROM TRACK;


-- 7. INVOICE
CREATE TABLE INVOICE (
    INVOICE_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    INVOICE_DATE DATE,
    BILLING_ADDRESS VARCHAR(255),
    BILLING_CITY VARCHAR(100),
    BILLING_STATE VARCHAR(100),
    BILLING_COUNTRY VARCHAR(100),
    BILLING_POSTAL_CODE VARCHAR(20),
    TOTAL DECIMAL(10,2),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

SELECT * FROM INVOICE;

-- 8. INVOICELINE
CREATE TABLE INVOICELINE (
    INVOICE_LINE_ID INT PRIMARY KEY,
    INVOICE_ID INT,
    TRACK_ID INT,
    UNIT_PRICE DECIMAL(10,2),
    QUANTITY INT,
    FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE(INVOICE_ID),
    FOREIGN KEY (TRACK_ID) REFERENCES TRACK(TRACK_ID)
);
SELECT * FROM INVOICELINE LIMIT 10;

-- 9. PLAYLIST
CREATE TABLE PLAYLIST (
    PLAYLIST_ID INT PRIMARY KEY,
    NAME VARCHAR(255)
);
SELECT * FROM PLAYLIST;


-- 10. PLAYLISTTRACK
CREATE TABLE PLAYLISTTRACK (
    PLAYLIST_ID INT,
    TRACK_ID INT,
    PRIMARY KEY (PLAYLIST_ID, TRACK_ID),
    FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLIST(PLAYLIST_ID),
    FOREIGN KEY (TRACK_ID) REFERENCES TRACK(TRACK_ID)
);
SELECT * FROM PLAYLISTTRACK LIMIT 100;




-- SENIOR MOST EMPLOYEE BASED ON JOB TITLE 

SELECT *
FROM EMPLOYEE
WHERE REPORTS_TO = 0;

-- . Which countries have the most Invoices?
SELECT BILLING_COUNTRY,
       COUNT(*) AS TOTAL_INVOICES
FROM INVOICE
GROUP BY BILLING_COUNTRY
ORDER BY TOTAL_INVOICES DESC
LIMIT 1;


-- WHAT ARE THE TOP 3 VALUES OF TOTAL INVOICE?
SELECT TOTAL
FROM INVOICE
ORDER BY TOTAL DESC
LIMIT 3;

-- WHICH CITY HAS THE BEST CUSTOMERS?
SELECT BILLING_CITY,
       SUM(TOTAL) AS TOTAL_REVENUE
FROM INVOICE
GROUP BY BILLING_CITY
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

-- WHO IS THE BEST CUSTOMER?
SELECT C.CUSTOMER_ID,
       C.FIRST_NAME,
       C.LAST_NAME,
       SUM(I.TOTAL) AS TOTAL_SPENT
FROM CUSTOMER C
JOIN INVOICE I
ON C.CUSTOMER_ID = I.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.FIRST_NAME, C.LAST_NAME
ORDER BY TOTAL_SPENT DESC
LIMIT 1;


-- ROCK MUSIC LISTENERS (EMAIL, NAME, GENRE)
SELECT DISTINCT C.EMAIL,
       C.FIRST_NAME,
       C.LAST_NAME,
       G.NAME AS GENRE
FROM CUSTOMER C
JOIN INVOICE I ON C.CUSTOMER_ID = I.CUSTOMER_ID
JOIN INVOICELINE IL ON I.INVOICE_ID = IL.INVOICE_ID
JOIN TRACK T ON IL.TRACK_ID = T.TRACK_ID
JOIN GENRE G ON T.GENRE_ID = G.GENRE_ID
WHERE G.NAME = 'ROCK'
ORDER BY C.EMAIL;

-- TOP 10 ROCK ARTISTS
SELECT AR.NAME AS ARTIST_NAME,
       COUNT(T.TRACK_ID) AS TRACK_COUNT
FROM ARTIST AR
JOIN ALBUM AL ON AR.ARTIST_ID = AL.ARTIST_ID
JOIN TRACK T ON AL.ALBUM_ID = T.ALBUM_ID
JOIN GENRE G ON T.GENRE_ID = G.GENRE_ID
WHERE G.NAME = 'ROCK'
GROUP BY AR.NAME
ORDER BY TRACK_COUNT DESC
LIMIT 10;

-- TRACKS LONGER THAN AVERAGE

SELECT NAME,
       MILLISECONDS
FROM TRACK
WHERE MILLISECONDS > (
    SELECT AVG(MILLISECONDS) FROM TRACK
)
ORDER BY MILLISECONDS DESC;


-- AMOUNT SPENT BY EACH CUSTOMER ON ARTISTS
SELECT C.FIRST_NAME,
       C.LAST_NAME,
       AR.NAME AS ARTIST_NAME,
       SUM(IL.UNIT_PRICE * IL.QUANTITY) AS TOTAL_SPENT
FROM CUSTOMER C
JOIN INVOICE I ON C.CUSTOMER_ID = I.CUSTOMER_ID
JOIN INVOICELINE IL ON I.INVOICE_ID = IL.INVOICE_ID
JOIN TRACK T ON IL.TRACK_ID = T.TRACK_ID
JOIN ALBUM AL ON T.ALBUM_ID = AL.ALBUM_ID
JOIN ARTIST AR ON AL.ARTIST_ID = AR.ARTIST_ID
GROUP BY C.FIRST_NAME, C.LAST_NAME, AR.NAME
ORDER BY TOTAL_SPENT DESC;

-- MOST POPULAR GENRE FOR EACH COUNTRY
SELECT I.BILLING_COUNTRY,
       G.NAME,
       COUNT(*) AS TOTAL
FROM INVOICE I,
     INVOICELINE IL,
     TRACK T,
     GENRE G
WHERE I.INVOICE_ID = IL.INVOICE_ID
AND IL.TRACK_ID = T.TRACK_ID
AND T.GENRE_ID = G.GENRE_ID
GROUP BY I.BILLING_COUNTRY, G.NAME
ORDER BY I.BILLING_COUNTRY, TOTAL DESC;



-- TOP CUSTOMER BY COUNTRY
SELECT I.BILLING_COUNTRY,
       C.FIRST_NAME,
       C.LAST_NAME,
       SUM(I.TOTAL) AS TOTAL
FROM CUSTOMER C,
     INVOICE I
WHERE C.CUSTOMER_ID = I.CUSTOMER_ID
GROUP BY I.BILLING_COUNTRY, C.FIRST_NAME, C.LAST_NAME
ORDER BY I.BILLING_COUNTRY, TOTAL DESC;